### ISSUE TITLE
Plug-in does not work after startup

### ISSUE THREAD

**Issue by lxmwwl** [Developer-Mike/obsidian-advanced-canvas#108] opened 2024-09-25 14:03 UTC

**Comment by Developer-Mike** [comment] 2024-10-03 09:13
Can you provide some more information like the version of Obsidian you're currently using?

**Comment by lxmwwl** [comment] 2024-10-04 00:05
> Can you provide some more information like the version of Obsidian you're currently using?

![image](https://github.com/user-attachments/assets/92298372-079d-4d53-9a71-46a24efb2ca7)
Every time I start ob, I need to close and reopen the plug-in to be useful. My ob version is 1.7.3, and the installation package is 1.6.7

**Comment by Developer-Mike** [comment] 2024-10-07 20:26
Thank you for the details. It's caused by the new [deferred views](https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views).

**Comment by Developer-Mike** [comment] 2024-10-08 17:41
Will probably be fixed in version `3.1.1` (I don't have a Catalyst license but according to the blog post the changes will fix this issue). I close this issue for now, but if it still occurs after the update, please reopen it immediately.

**Comment by torstenkoepke** [comment] 2024-10-09 18:33
#As you requested: 3.1.1 did not fix the issue - the plugin has to be switched off and on to be usable.

**Comment by Developer-Mike** [comment] 2024-10-09 18:46
😩 Thank you for letting me know.

**Comment by Developer-Mike** [comment] 2024-10-13 09:00
I was able to fix it in version `3.1.2` (By buying a Catalyst license myself 😉)

**Closed by Developer-Mike** 2024-10-13 09:00 UTC
Labels: bug, high-priority

**Comment by lxmwwl** [comment] 2024-10-13 12:49
> I was able to fix it in version `3.1.2` (By buying a Catalyst license myself 😉)

Thanks
