### ISSUE TITLE
Not working with Latest Development Version 1.7.3

### ISSUE THREAD

**Issue by martin-dunban** [Developer-Mike/obsidian-advanced-canvas#110] opened 2024-10-07 18:00 UTC
Plugin appears to work with latest development release 1.7.3 [tested on Desktop Windows 11]. I understand that there may have been API changes in 1.7.3 that could be the cause of the problem.

**Comment by Developer-Mike** [comment] 2024-10-07 20:18
Duplicate of #108

**Closed** 2024-10-07 20:19 UTC
Labels: bug, duplicate, high-priority
