### ISSUE TITLE
after installing your app, Obsidian1.5.11 is not able to create canvas file

### ISSUE THREAD

**Issue by josephlam7** [Developer-Mike/obsidian-advanced-canvas#39] opened 2024-03-23 22:03 UTC

**Comment by Developer-Mike** [comment] 2024-03-24 07:13
Duplicate of #38

**Closed by Developer-Mike** 2024-03-24 07:13 UTC

**Comment by josephlam7** [comment] 2024-03-26 01:13
Not sure how posting a problem in Your GitHub page works, but just to say,
my problem is solved now.
Thank you for you tremendous work in coming out with this wonderful plugin

Joseph

**Comment by Developer-Mike** [comment] 2024-03-26 06:06
Thank you for your update and your kind words 🙏🏻
